export enum CssVariables  {
  white='var(--white)',
  black='var(--black)',
  navigationTabBackground='var(--navigationTabBackground)',
  activeNAvigationTabBackground='var(--activeNAvigationTabBackground)',
  navigationTabTextColor='var(--navigationTabTextColor)',
  lightBlue='var(--lightBlue)',
  mildBlue='var(--mildBlue)',
  primaryBlue='var(--primaryBlue)',
  paperBorderRadius='var(--paperBorderRadius)',
  darkText='var(--darkText)',
  error='var(--error)',
  grey='var(--grey)',
  green='var(--green)',
  mildGreen='var(--mildGreen)',
  red='var(--red)',
  mildRed='var(--mildRed)',
  lightGrey='var(--lightGrey)',

}