export const env = {
  ANALYTICS_ENDPOINT: process.env.REACT_APP_ANALYTICS_ENDPOINT,
  APIADDR: process.env.REACT_APP_APIADDR,
  APPNAME: process.env.REACT_APP_APPNAME,
  DEVAPIADDR: process.env.REACT_APP_DEVAPIADDR,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
  IPFS_API_URL: process.env.REACT_APP_IPFS_API_URL,
  LOCALNODE: process.env.REACT_APP_LOCALNODE,
  NETWORK: process.env.REACT_APP_NETWORK,
  PRIVATENODE: process.env.REACT_APP_PRIVATENODE,
}