#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building the project before committing'

# Check ESLint Standards
npm run lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run checkTs ||
(
    echo 'Failed Type check.
    Make the changes required above.'
    false;
)

# If everything passes... Now we can commit

echo '✅✅✅✅ all good. ✅✅✅✅'
